title: My Portfolio
author: Morsheda Jeba
email: morshedajeba@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Hi there! This is Jeba. I'm an undergraduate CS student.

# social links
twitter_username: https://twitter.com/JebaMorsheda # DO NOT include the @ character, or else the build will fail!
github_username:  https://github.com/Morsheda # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
