title: Portfolio
author: Morsheda Jeba
email: ms_jeba97@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Hi there! This is Jeba. I'm an undergraduate student persuing my B.Sc. degree in Computer Science & Engineering.
# social links
twitter_username:  https://twitter.com/JebaMorsheda
github_username:  https://github.com/Morsheda

show_excerpts: true # set to false to remove excerpts on the homepage
